version: '3.9'
services:
  corda-registration:
    environment:
      CORDA_ARGS: --initial-registration --network-root-truststore /tmp/network-truststore.jks --network-root-truststore-password trustpass
    volumes:
      - './certificates:/opt/corda/certificates'
      - './node.conf:/etc/corda/node.conf'
      - './network-truststore.jks:/tmp/network-truststore.jks'
    ports:
      - '10006:10006'
      - '10005:10005'
    container_name: corda-BDI-node-registration
    image: 'corda/community:4.9.2-zulu-openjdk8'
    user: root
    profiles:
      - registration
    networks:
      - BDI-node-net


  corda-database-migration:
    environment:
      CORDA_ARGS: run-migration-scripts --core-schemas --allow-hibernate-to-manage-app-schema --config-file=/etc/corda/node.conf
    volumes:
      - './certificates:/opt/corda/certificates'
      - './node.conf:/etc/corda/node.conf'
      - './network-truststore.jks:/tmp/network-truststore.jks'
      - './cordapps:/opt/corda/cordapps'
      - './persistence:/opt/corda/persistence'
      - './database.properties:/opt/corda/database.properties'
    ports:
      - '10006:10006'
      - '10005:10005'
    container_name: corda-BDI-node-migration
    image: 'corda/community:4.9.2-zulu-openjdk8'
    user: root
    profiles:
      - db
    networks:
      - BDI-node-net

  corda:
    environment:
      triplestore.host: "graphdb"
    volumes:
      - './certificates:/opt/corda/certificates'
      - './node.conf:/etc/corda/node.conf'
      - './network-truststore.jks:/tmp/network-truststore.jks'
      - './cordapps:/opt/corda/cordapps'
      - './persistence:/opt/corda/persistence'
      - './database.properties:/opt/corda/database.properties'
      - './ishare.properties:/opt/corda/ishare.properties'
    ports:
      - '10006:10006'
      - '10005:10005'
    container_name: corda-BDI-node
    image: 'corda/community:4.9.2-zulu-openjdk8'
    user: root
    profiles:
      - run
    networks:
      - BDI-node-net

  spring:
    environment:
      cordaHost: "corda"
      cordaPort: 10006
      cordaUser: "user1"
      cordaPassword: "vzzuABeCut3jGoJfEp94"
      springPort: 10050
    ports:
      - '10050:10050'
    depends_on:
      - corda
    image: 'chirvasutatc/bdi-api:0.1'
    container_name: bdi-api
    command: /bin/bash -c "java -Dserver.port=$$springPort -Dconfig.rpc.host=$$cordaHost -Dconfig.rpc.port=$$cordaPort -Dconfig.rpc.username=$$cordaUser -Dconfig.rpc.password=$$cordaPassword -jar api.jar"
    profiles:
      - run
    networks:
      - BDI-node-net
    restart: on-failure

  graphdb:
    volumes:
      - './graphdb-data:/opt/graphdb/data'
    ports:
      - '7200:7200'
    image: 'khaller/graphdb-free:10.0.0'
    container_name: graphdb
    profiles:
      - run
    networks:
      - BDI-node-net

networks:
  BDI-node-net: {}
